// Comprehensive currency code → country name mapping
// Covers all major world currencies + crypto
const CURRENCY_MAP = {
    aed: "United Arab Emirates",
    afn: "Afghanistan",
    all: "Albania",
    amd: "Armenia",
    ang: "Curaçao",
    aoa: "Angola",
    ars: "Argentina",
    aud: "Australia",
    awg: "Aruba",
    azn: "Azerbaijan",
    bam: "Bosnia & Herzegovina",
    bbd: "Barbados",
    bdt: "Bangladesh",
    bgn: "Bulgaria",
    bhd: "Bahrain",
    bif: "Burundi",
    bmd: "Bermuda",
    bnd: "Brunei",
    bob: "Bolivia",
    brl: "Brazil",
    bsd: "Bahamas",
    btn: "Bhutan",
    bwp: "Botswana",
    byn: "Belarus",
    bzd: "Belize",
    cad: "Canada",
    cdf: "Congo (DRC)",
    chf: "Switzerland",
    clp: "Chile",
    cny: "China",
    cop: "Colombia",
    crc: "Costa Rica",
    cuc: "Cuba (CUC)",
    cup: "Cuba (CUP)",
    cve: "Cape Verde",
    czk: "Czech Republic",
    djf: "Djibouti",
    dkk: "Denmark",
    dop: "Dominican Republic",
    dzd: "Algeria",
    egp: "Egypt",
    ern: "Eritrea",
    etb: "Ethiopia",
    eur: "European Union",
    fjd: "Fiji",
    fkp: "Falkland Islands",
    gbp: "United Kingdom",
    gel: "Georgia",
    ghs: "Ghana",
    gip: "Gibraltar",
    gmd: "Gambia",
    gnf: "Guinea",
    gtq: "Guatemala",
    gyd: "Guyana",
    hkd: "Hong Kong",
    hnl: "Honduras",
    hrk: "Croatia",
    htg: "Haiti",
    huf: "Hungary",
    idr: "Indonesia",
    ils: "Israel",
    inr: "India",
    iqd: "Iraq",
    irr: "Iran",
    isk: "Iceland",
    jmd: "Jamaica",
    jod: "Jordan",
    jpy: "Japan",
    kes: "Kenya",
    kgs: "Kyrgyzstan",
    khr: "Cambodia",
    kmf: "Comoros",
    kpw: "North Korea",
    krw: "South Korea",
    kwd: "Kuwait",
    kyd: "Cayman Islands",
    kzt: "Kazakhstan",
    lak: "Laos",
    lbp: "Lebanon",
    lkr: "Sri Lanka",
    lrd: "Liberia",
    lsl: "Lesotho",
    lyd: "Libya",
    mad: "Morocco",
    mdl: "Moldova",
    mga: "Madagascar",
    mkd: "North Macedonia",
    mmk: "Myanmar",
    mnt: "Mongolia",
    mop: "Macau",
    mru: "Mauritania",
    mur: "Mauritius",
    mvr: "Maldives",
    mwk: "Malawi",
    mxn: "Mexico",
    myr: "Malaysia",
    mzn: "Mozambique",
    nad: "Namibia",
    ngn: "Nigeria",
    nio: "Nicaragua",
    nok: "Norway",
    npr: "Nepal",
    nzd: "New Zealand",
    omr: "Oman",
    pab: "Panama",
    pen: "Peru",
    pgk: "Papua New Guinea",
    php: "Philippines",
    pkr: "Pakistan",
    pln: "Poland",
    pyg: "Paraguay",
    qar: "Qatar",
    ron: "Romania",
    rsd: "Serbia",
    rub: "Russia",
    rwf: "Rwanda",
    sar: "Saudi Arabia",
    sbd: "Solomon Islands",
    scr: "Seychelles",
    sdg: "Sudan",
    sek: "Sweden",
    sgd: "Singapore",
    shp: "Saint Helena",
    sll: "Sierra Leone",
    sos: "Somalia",
    srd: "Suriname",
    ssp: "South Sudan",
    std: "São Tomé & Príncipe",
    syp: "Syria",
    szl: "Eswatini",
    thb: "Thailand",
    tjs: "Tajikistan",
    tmt: "Turkmenistan",
    tnd: "Tunisia",
    top: "Tonga",
    try: "Turkey",
    ttd: "Trinidad & Tobago",
    twd: "Taiwan",
    tzs: "Tanzania",
    uah: "Ukraine",
    ugx: "Uganda",
    usd: "United States",
    uyu: "Uruguay",
    uzs: "Uzbekistan",
    ves: "Venezuela",
    vnd: "Vietnam",
    vuv: "Vanuatu",
    wst: "Samoa",
    xaf: "Central Africa (CEMAC)",
    xcd: "East Caribbean",
    xof: "West Africa (UEMOA)",
    xpf: "French Polynesia",
    yer: "Yemen",
    zar: "South Africa",
    zmw: "Zambia",
    zwl: "Zimbabwe",
    // Crypto
    btc: "Bitcoin",
    eth: "Ethereum",
    bnb: "BNB Chain",
    ada: "Cardano",
    dot: "Polkadot",
    sol: "Solana",
    doge: "Dogecoin",
    xrp: "Ripple",
    ltc: "Litecoin",
    link: "Chainlink",
};

/**
 * Get country name for a currency code.
 * Returns the uppercase code if not found.
 */
export function getCountryName(code) {
    return CURRENCY_MAP[code?.toLowerCase()] || code?.toUpperCase() || "Unknown";
}

/**
 * Search currencies by country name.
 * Returns array of matching currency codes.
 */
export function searchByCountry(query, availableCurrencies = []) {
    if (!query || query.trim().length === 0) return [];
    const lower = query.toLowerCase().trim();
    return availableCurrencies.filter((code) => {
        const country = CURRENCY_MAP[code]?.toLowerCase() || "";
        return country.includes(lower) || code.includes(lower);
    });
}

export default CURRENCY_MAP;
